name: Docs deploy

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'The run id of the workflow building the docs'
        required: true
      pr_number:
        description: 'The pull request number for deploying a PR preview, if applicable'
        default: ''
        required: false

env:
  html_folder: ./doc/_build/html
  artifact_name: doc_html

jobs:

  deploy:
    # if: github.repository == 'pyxem/pyxem'
    runs-on: ubuntu-latest
    steps:
      - name: Download built docs
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.html_folder }}
          # need to specify the run id to get the artifact from the correct workflow run
          # and set the github-token to access the actions scope
          # https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories
          run-id: ${{ inputs.workflow_run_id }}
          github-token: ${{ github.token }}

      - name: Print doc files
        run: ls -l ${{ env.html_folder }}

      - name: Deploy dev
        # run on main branch only
        if: github.ref_name == 'main' 
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.html_folder }}
          destination_dir: dev

      - name: Deploy PR preview
        # run on pull request only
        if: inputs.pr_number != ''
        uses: ./.github/actions/doc_preview
        with:
          source-dir: ${{ env.html_folder }}
          deploy-repository: CSSFrancis/pyxem-docs-staging
          token: ${{ secrets.PREVIEW_DEPLOY_KEY }}
          comment: true
          pr-number: ${{ inputs.pr_number }}

      - name: Deploy versioned docs
        # run on tag only
        if: github.ref_type == 'tag'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir:  ${{ env.html_folder }}
          destination_dir: ${{ github.ref_name }} # deploy to a folder matching the tag version

      - name: Download redirect files
        # run on tag only
        if: github.ref_type == 'tag'
        uses: actions/download-artifact@v5
        with:
          name: redirect
          path: redirect
          # need to specify the run id to get the artifact from the correct workflow run
          # and set the github-token to access the actions scope
          # https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories
          run-id: ${{ inputs.workflow_run_id }}
          github-token: ${{ github.token }}

      - name: Deploy redirect to versioned docs
        # run on tag only
        if: github.ref_type == 'tag'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir:  redirect
          destination_dir: . # deploy the redirect to the root folder
          keep_files: true
