name: Docs deploy

on:
  workflow_run:
    workflows: ["Docs build"]
    types: [completed]

env:
  html_folder: ./doc/_build/html
  artifact_name: doc_html

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Download deploy info artifact
        uses: actions/download-artifact@v5
        with:
          name: deploy-info
          path: deploy_info
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse deploy info
        id: info
        run: |
          echo "Parsing deploy_info/info.json:"
          cat deploy_info/info.json
          echo "workflow_run_id=$(jq -r '.workflow_run_id' deploy_info/info.json)" >> $GITHUB_OUTPUT # to get the run id of the workflow that built the docs
          echo "pr_number=$(jq -r '.pr_number' deploy_info/info.json)" >> $GITHUB_OUTPUT # empty if not a PR
          echo "pull_request_action=$(jq -r '.pull_request_action' deploy_info/info.json)" >> $GITHUB_OUTPUT # 'The pull request event action that triggered the workflow building the docs (e.g. opened, closed, synchronize)'
      
      # need to specify the run id to get the artifact from the correct workflow run
      # and set the github-token to access the actions scope
      # https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories
      - name: Download built docs
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.html_folder }}
          run-id: ${{ steps.info.outputs.workflow_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print doc files
        run: ls -l ${{ env.html_folder }}

      - name: Deploy PR preview
       # run on pull request only
        # until rossjrw/pr-preview-action suppports passing the PR number as input,
        # use the peaceiris/actions-gh-pages and implement cleanup on PR closed
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action != 'closed' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          personal_token: ${{ secrets.PREVIEW_DEPLOY_KEY }}
          publish_dir:  ${{ env.html_folder }}
          destination_dir: pr-preview/${{ steps.info.outputs.pr_number }}
          external_repository: CSSFrancis/pyxem-docs-staging

      - name: Get timestamp (UTC)
        if: ${{ steps.info.outputs.pr_number != '' }}
        id: timestamp
        run: |
          echo "utc=$(date -u '+%Y-%m-%d %H:%M UTC')" >> "$GITHUB_OUTPUT"

      - name: Post preview link as sticky PR comment
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action != 'closed' }}
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        with:
          number: ${{ steps.info.outputs.pr_number }}
          header: pr-preview
          message: |
            **PR Preview**
            :---:
            :rocket: View PR Preview at https://cssfrancis.github.io/pyxem-docs-staging/pr-preview/pr-${{ steps.info.outputs.pr_number }}.
            If you see a 404 error, please wait a few seconds for the deployment to complete and refresh the page.
            ${{ steps.timestamp.outputs.utc }}

      - name: Create empty deploy folder
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action == 'closed' }}
        run: mkdir -p empty

      - name: Remove PR preview
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action == 'closed' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          personal_token: ${{ secrets.PREVIEW_DEPLOY_KEY }}
          publish_dir: ./empty
          destination_dir: pr-preview/${{ steps.info.outputs.pr_number }}
          external_repository: CSSFrancis/pyxem-docs-staging

      - name: Update sticky PR comment
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action == 'closed' }}
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        with:
          number: ${{ steps.info.outputs.pr_number }}
          header: pr-preview
          message: |
            **PR Preview**
            :---:
            Preview removed because the pull request was closed.
            ${{ steps.timestamp.outputs.utc }}
